_commit: 0.0.2rc-62-g52ffbf3
_src_path: gh:bswck/skeleton
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Convenient lazy imports for Python.
docs: true
email: bswck.dev@gmail.com
github: bswck
license: MIT
package: lazy_imports
precommit: true
pypi: true
pypi_description: Convenient lazy imports for Python.
pypi_project_name: lazy-imports
pypy: true
python: '3.8'
repo: lazy-imports
rtd: lazy-imports
tests: true
visibility: public
