_commit: 0.0.2rc-219-g781ce0c
_src_path: gh:skeleton-ci/skeleton-python
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Convenient lazy importing in Python.
docs: true
email: bartoszpiotrslawecki@gmail.com
github: bswck
license: MIT
package: lazy_importing
precommit: true
pypi: true
pypi_description: Convenient lazy importing in Python.
pypi_project: lazy-importing
pypy: true
python: '3.8'
python_until: ''
repo: lazy-importing
rtd: lazy-importing
tests: true
tidelift: false
visibility: public
wip: true
