_commit: 0.0.2rc-238-g68b0ab8
_src_path: gh:skeleton-ci/skeleton-python
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Super-easy lazy importing in Python.
docs: true
email: bartoszpiotrslawecki@gmail.com
github: bswck
license: MIT
package: slothy
precommit: true
pypi: true
pypi_description: Super-easy lazy importing in Python.
pypi_project: slothy
pypy: true
python: '3.8'
python_until: ''
repo: slothy
rtd: slothy
tests: true
tidelift: false
visibility: public
wip: false
